"""Machine-Native Experimental Learning."""

from .core import (
    EvidenceLedger,
    HardGateEvaluator,
    RecursionGovernor,
    VerifiedExperienceDistiller,
    canonical_digest,
)
from .learned_providers import (
    DEFAULT_LEARNED_PROVIDER_REGISTRY,
    LearnedProviderDeclaration,
    LearnedProviderObservation,
    LearnedProviderQuery,
    LearnedProviderRegistry,
)
from .one_step_specialist import (
    DistillationDataset,
    FallbackResult,
    OneStepSpecialistError,
    OneStepStudentDecision,
    OneStepStudentModel,
    StudentCalibration,
    StudentOperatingEnvelope,
    TargetStatus,
    TeacherObservation,
    build_distillation_dataset,
    build_one_step_reference_artifacts,
    calibrate_one_step_student,
    collect_teacher_observation,
    infer_with_teacher_fallback,
    train_one_step_student,
)
from .placement import (
    AcceleratorDiagnostics,
    ExecutionDevice,
    ExecutionMode,
    OffloadMode,
    PlacementCapabilities,
    PlacementDecision,
    PlacementPolicy,
    Precision,
    decide_placement,
)
from .provider_runtime import (
    ExecutionTier,
    ImplementationLanguage,
    NativeLanguageException,
    ProviderRuntimeManifest,
    load_runtime_manifest,
)
from .recurrent_specialist import (
    CalibrationRecord,
    OperatingEnvelope,
    RecurrentSpecialistModel,
    SpecialistContextState,
    SpecialistDecision,
    SpecialistError,
    build_reference_artifacts,
    calibrate_recurrent_specialist,
    context_update,
    infer_batch,
    train_recurrent_specialist,
)

__all__ = [
    "DEFAULT_LEARNED_PROVIDER_REGISTRY",
    "AcceleratorDiagnostics",
    "CalibrationRecord",
    "DistillationDataset",
    "EvidenceLedger",
    "ExecutionDevice",
    "ExecutionMode",
    "ExecutionTier",
    "FallbackResult",
    "HardGateEvaluator",
    "ImplementationLanguage",
    "LearnedProviderDeclaration",
    "LearnedProviderObservation",
    "LearnedProviderQuery",
    "LearnedProviderRegistry",
    "NativeLanguageException",
    "OffloadMode",
    "OneStepSpecialistError",
    "OneStepStudentDecision",
    "OneStepStudentModel",
    "OperatingEnvelope",
    "PlacementCapabilities",
    "PlacementDecision",
    "PlacementPolicy",
    "Precision",
    "ProviderRuntimeManifest",
    "RecurrentSpecialistModel",
    "RecursionGovernor",
    "SpecialistContextState",
    "SpecialistDecision",
    "SpecialistError",
    "StudentCalibration",
    "StudentOperatingEnvelope",
    "TargetStatus",
    "TeacherObservation",
    "VerifiedExperienceDistiller",
    "build_distillation_dataset",
    "build_one_step_reference_artifacts",
    "build_reference_artifacts",
    "calibrate_one_step_student",
    "calibrate_recurrent_specialist",
    "canonical_digest",
    "collect_teacher_observation",
    "context_update",
    "decide_placement",
    "infer_batch",
    "infer_with_teacher_fallback",
    "load_runtime_manifest",
    "train_one_step_student",
    "train_recurrent_specialist",
]

__version__ = "0.1.0a0"
